#!/bin/sh

### BEGIN INIT INFO
# Provides:          wsopenjkn
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Web Service Mobile JKN
### END INIT INFO

SCRIPT=/opt/ws_openjkn/wsopenjkn_wrap.sh
RUNAS=devuser

EXENAME=ws_openjkn
PIDFILE=/opt/ws_openjkn/run/wsopenjkn.pid
LOGFILE=/opt/ws_openjkn/run/wsopenjkn.log

start() {
  if [ -f "$PIDFILE" ] && kill -0 $(pidof "$EXENAME"); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  #if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(pidof "$EXENAME"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  #kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  kill -15 $(pidof "$EXENAME") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f wsopenjkn remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac
